-- drop objects
drop table ex_departments cascade constraints;
drop table ex_citys cascade constraints;
drop table ex_stores cascade constraints;
drop table ex_employees cascade constraints;
drop table ex_products cascade constraints;

-- create tables
create table ex_departments (
    id                             number generated by default on null as identity 
                                   constraint ex_departments_id_pk primary key,
    name                           varchar2(50 char)
                                   constraint ex_departments_name_unq unique not null
)
;

create table ex_citys (
    id                             number generated by default on null as identity 
                                   constraint ex_citys_id_pk primary key,
    department_id                  number
                                   constraint ex_citys_department_id_fk
                                   references ex_departments on delete cascade,
    name                           varchar2(100 char)
                                   constraint ex_citys_name_unq unique not null
)
;

-- table index
create index ex_citys_i1 on ex_citys (department_id);

create table ex_stores (
    id                             number generated by default on null as identity 
                                   constraint ex_stores_id_pk primary key,
    city_id                        number
                                   constraint ex_stores_city_id_fk
                                   references ex_citys on delete cascade,
    name                           varchar2(30 char)
                                   constraint ex_stores_name_unq unique not null,
    administrator                  number
                                   constraint ex_stores_administrator_fk
                                   references ex_employees on delete cascade not null
)
;

-- table index
create index ex_stores_i1 on ex_stores (administrator);
create index ex_stores_i2 on ex_stores (city_id);

create table ex_employees (
    id                             number generated by default on null as identity 
                                   constraint ex_employees_id_pk primary key,
    store_id                       number
                                   constraint ex_employees_store_id_fk
                                   references ex_stores on delete cascade,
    name                           varchar2(255 char) not null,
    position                       varchar2(40 char) not null,
    email                          varchar2(200 char) not null,
    hiring_date                    date not null,
    boss                           number
                                   constraint ex_employees_boss_fk
                                   references ex_employees on delete cascade not null
)
;

-- table index
create index ex_employees_i1 on ex_employees (boss);
create index ex_employees_i2 on ex_employees (store_id);

create table ex_products (
    id                             number generated by default on null as identity 
                                   constraint ex_products_id_pk primary key,
    store_id                       number
                                   constraint ex_products_store_id_fk
                                   references ex_stores on delete cascade,
    name                           varchar2(50 char)
                                   constraint ex_products_name_unq unique not null,
    gross_value                    number not null,
    discount_rate_max              number not null,
    net_price                      number not null,
    description                    varchar2(1000 char)
)
;

-- table index
create index ex_products_i1 on ex_products (store_id);


-- triggers
create or replace editionable trigger ex_employees_biu
    before insert or update 
    on ex_employees
    for each row
begin
    :new.email := lower(:new.email);
end ex_employees_biu;
/

-- load data
 
insert into ex_departments (
    id,
    name
) values (
    1,
    'Tax Compliance'
);

commit;
-- load data
select 
    ID,
    NAME
from EX_DEPARTMENTS;

-- load data
 
insert into ex_citys (
    id,
    department_id,
    name
) values (
    1,
    1,
    'Load Balancer Certificate Upgrade'
);

commit;
select 
    ID,
    DEPARTMENT_ID,
    NAME
from EX_CITYS;

-- load data
 
insert into ex_stores (
    id,
    city_id,
    name,
    administrator
) values (
    1,
    1,
    'Load Balancer Certificate Upgr',
    1
);

commit;
select 
    ID,
    CITY_ID,
    NAME,
    ADMINISTRATOR
from EX_STORES;

-- load data
 
insert into ex_employees (
    id,
    store_id,
    name,
    position,
    email,
    hiring_date,
    boss
) values (
    1,
    1,
    'Gricelda Luebbers',
    'Lacinialectus Quis Consectetur',
    'gricelda.luebbers@aaab.com',
    sysdate - 55,
    1
);

commit;
select 
    ID,
    STORE_ID,
    NAME,
    POSITION,
    EMAIL,
    HIRING_DATE,
    BOSS
from EX_EMPLOYEES;

-- load data
 
insert into ex_products (
    id,
    store_id,
    name,
    gross_value,
    discount_rate_max,
    net_price,
    description
) values (
    1,
    1,
    'M-AABN-39',
    37,
    3,
    59,
    'Viverra lacinialectus, quis consectetur mi venenatis nec. Donec convallis sollicitudin elementum. Nulla facilisi. In posuere blandit leoeget malesuada. Vivamus efficitur ipsum tellus, quis posuere mi maximus vitae. Quisque tortor odio, feugiat eget sagittisvel, pretium ut metus. Duis et commodo arcu, in vestibulum tellus. In sollicitudin nisi mi, pharetra gravida ex semper ut.Donec nibh sapien, hendrerit quis varius eget, malesuada vitae turpis. Lorem ipsum dolor sit amet, consectetur adipiscing elit.Vivamus sapien sem, volutpat vitae luctus vitae, pretium.'
);

commit;
select 
    ID,
    STORE_ID,
    NAME,
    GROSS_VALUE,
    DISCOUNT_RATE_MAX,
    NET_PRICE,
    DESCRIPTION
from EX_PRODUCTS;

